language: python

python:
  - "3.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install black pytest sphinx coveralls

script:
  - black .
  - coverage run -m pytest tests
  - cd docs && make clean && make html && cd ..

after_success:
- coveralls

notifications:
  email: false
